// FX Studio — the screens (ARCHITECTURE §7, the first door), built on the API and nothing else.
// THREE TABS since step 5 (2026-09-07): FX (every FX in one list, grouped Draft → House → Stock,
// ui/fxtab.js), Assets (ui/library.js) and Coverage (the compendiums the user picks, read once and
// asked what plays; what did not resolve; the maintainer's card). Stock FX and House FX were the
// same list twice, differing by a filter on `source`, and Look up was a search with a card: the
// search now lives in the window header and answers on every tab, and its card is the FX tab's own
// detail pane. THE FX SHEET IS A PANE, NOT A TAB (ui/sheet.js): it is opened on an FX and its Back
// returns to wherever it was opened from.
// Labels are terms; the one sentence per FX is generated by core/fx.js and never parsed back. One
// window, plain DOM: ApplicationV2 with its own _renderHTML, no template engine.
import { MODULE_ID } from '../settings.js';
import { keyLabel, parseKey, slug } from '../core/subjects.js';
import { SOURCE_TAG, STATUS_WORDS, dot, esc, idWords, statusOf } from './html.js';
import { hydrateSheet, leaveSheet, onSheetChange, onSheetClick, onSheetInput, onSheetKey, openSheet, renderSheet, sheetDirty } from './sheet.js';
import { onCorpusChange, onCorpusClick, renderMaintain } from './corpus.js';
import { onFxChange, onFxClick, renderFx } from './fxtab.js';
import { onLibraryChange, onLibraryClick, onLibraryInput, renderLibrary } from './library.js';

const api = () => game.modules.get(MODULE_ID).api;
const TABS = [['fx', 'FX'], ['assets', 'Assets'], ['coverage', 'Coverage']];
/** the tabs step 5 replaced, so a macro, a bridge or an old call still lands where it meant to */
const WAS = { stock: 'fx', house: 'fx', lookup: 'fx', library: 'assets', audit: 'coverage' };

const ApplicationV2 = globalThis.foundry?.applications?.api?.ApplicationV2 ?? class { constructor() {} render() {} };

export class Studio extends ApplicationV2 {
  static DEFAULT_OPTIONS = {
    id: 'fxstudio',
    classes: ['fxstudio'],
    window: { title: 'FX Studio', icon: 'fa-solid fa-wand-sparkles', resizable: true, contentClasses: ['fxstudio-content'] },
    // the FX tab is three columns (facets · rows · the 300px pane), so the window opens at the width
    // the screens were ruled at; narrower still works — nothing rearranges, the sentence ellipsises
    position: { width: 1080, height: 800 },
  };

  /** the one open window, so the sheet button and the API reuse it */
  static current = null;

  constructor(options = {}) {
    super(options);
    this.view = { tab: 'fx', subject: null, fxSel: null, q: '', books: null, chosenBooks: new Set(), reading: false };
    this.sheet = null;
    this.co = null;
    this._bound = false;
  }

  /** open the window at a tab, on an item, on a key, or on an FX id; tab 'editor' opens the sheet on it */
  static open({ tab = null, item = null, id = null, key = null, edit = false } = {}) {
    const app = Studio.current ?? (Studio.current = new Studio());
    if (!app.entries) app.refresh();
    const want = tab ? (WAS[tab] ?? tab) : null;
    if (want) app.view.tab = want;
    if (tab === 'editor') {
      if (item) app.openFor(app.subjectFromItem(item), { edit });
      else if (id) openSheet(app, { id, edit });
      else if (key) app.openFor(app.subjectForKey(key), { edit });
      else if (!app.sheet) openSheet(app, {});
    } else if (item) app.showItem(item);
    else if (key) app.showKey(key);
    else if (id) app.showFx(id);
    app.render({ force: true });
    if (app.rendered) app.bringToFront?.();
    return app;
  }

  async close(options) {
    if (sheetDirty(this) && !(await leaveSheet(this))) return this;
    Studio.current = null;
    return super.close(options);
  }

  // -------------------------------------------------------------------------------------------
  // the index of what can be looked up: every ability on every actor, then every key the corpus knows
  // -------------------------------------------------------------------------------------------
  refresh() {
    const a = api();
    this.census = a.census();
    const entries = [];
    for (const row of this.census.actors) {
      for (const it of row.items) entries.push({ name: it.name, owner: row.name, actorType: row.type, uuid: it.uuid, keys: it.keys, hasPlace: it.hasPlace, on: 'use', status: statusOf(it), type: it.type });
      for (const ef of row.effects) entries.push({ name: ef.name, owner: row.name, actorType: row.type, keys: ef.keys, on: 'effect', status: statusOf(ef), type: 'effect', effect: true });
    }
    const seen = new Set(entries.flatMap((e) => e.keys));
    for (const { fx, source } of a.fx.list()) {
      for (const key of fx.for ?? []) {
        if (seen.has(key)) continue;
        seen.add(key);
        entries.push({ name: keyLabel(key), key, keys: [key], on: fx.on ?? 'use', owner: null, status: fx.off ? 'off' : (source === 'stock' ? 'stock' : 'custom'), corpus: true });
      }
    }
    this.entries = entries;
    this._shelf = null;
    // the FX tab reads every FX once per rebuild, not once per keystroke
    this._catalogue = null;
    this._broken = null;
    // an FX deleted for good cannot stay selected in the pane
    if (this.view.fxSel && !a.fx.get(this.view.fxSel)) this.view.fxSel = null;
  }

  // -------------------------------------------------------------------------------------------
  // subjects: what a card or a walk is about — {name, keys, pointer, uuid, owner, actor, hasPlace, on, kind, isNew}
  // -------------------------------------------------------------------------------------------
  subjectFromItem(item) {
    const a = api();
    const acts = item.system?.activities?.contents ?? [];
    const hasPlace = acts.some((x) => x?.target?.template?.type);
    const subject = a.subjects.ofItem(item, { activity: acts[0] ?? null });
    return { name: item.name, keys: subject.keys, pointer: subject.pointer ?? null, uuid: item.uuid, owner: item.actor?.name ?? null, actor: item.actor ?? null, hasPlace, on: 'use', kind: subject.kind };
  }
  subjectFromEntry(e) {
    if (e.uuid) { const item = fromUuidSync(e.uuid); if (item) return this.subjectFromItem(item); }
    return { name: e.name, keys: e.keys, owner: e.owner, hasPlace: !!e.hasPlace, on: e.on ?? 'use', kind: parseKey(e.keys[0])?.kind ?? 'spell' };
  }
  subjectForKey(key) {
    const p = parseKey(key);
    const e = this.entries?.find((x) => x.keys.includes(key));
    if (e) return this.subjectFromEntry(e);
    return { name: idWords(p?.id ?? key), keys: [key], owner: null, hasPlace: false, on: p?.kind === 'effect' ? 'effect' : 'use', kind: p?.kind ?? 'spell' };
  }
  subjectForFx(id) {
    const entry = api().fx.get(id);
    const key = entry?.fx?.for?.[0];
    if (key) return this.subjectForKey(key);
    return { name: idWords(id), keys: [], owner: null, hasPlace: false, on: entry?.fx?.on ?? 'use', kind: 'spell', fxId: id };
  }
  /** a name typed that is on no sheet: a new ability, keyed by its name as the kind the user picks */
  subjectNew(name, kind = 'spell') {
    return { name, keys: [`${kind}:${slug(name)}`], owner: null, hasPlace: false, on: kind === 'effect' ? 'effect' : 'use', kind, isNew: true };
  }

  /** the sheet for what a subject plays: the FX that answers it, or a new one for it */
  openFor(subject, { edit = false } = {}) {
    const r = this.answerFor(subject);
    const id = r?.original?.id ?? null;
    if (id) return openSheet(this, { id, subject, edit });
    return openSheet(this, { subject, edit: true });
  }

  /** the item on a sheet whose pointer names this FX: {actor, item}, or null */
  ownerOfFx(id) {
    for (const row of this.census.actors) for (const it of row.items) {
      const item = it.uuid ? fromUuidSync(it.uuid) : null;
      if (item?.flags?.[MODULE_ID]?.fx === id) return { actor: row.name, item: item.name };
    }
    return null;
  }

  /**
   * The header search answered: the subject, the FX that answers it selected in the pane, and the
   * box carrying what was asked (so the list is narrowed to it too). Picking a row is not an ask —
   * it must not move the list out from under the click — so showFx passes ask: false.
   */
  show(subject, { ask = true } = {}) {
    this.view.subject = subject;
    this.view.fxSel = this.answerFor(subject)?.original?.id ?? null;
    if (ask && subject?.name) this.view.q = subject.name;
    this.view.tab = 'fx';
  }
  showItem(item) { this.show(this.subjectFromItem(item)); }
  showEntry(e) { this.show(this.subjectFromEntry(e)); }
  showKey(key) { this.show(this.subjectForKey(key)); }
  showFx(id) { this.show(this.subjectForFx(id), { ask: false }); this.view.fxSel = id; }
  showNew(name, kind = 'spell') { this.show(this.subjectNew(name, kind)); }

  /** what a subject plays, through the API */
  answerFor(s) {
    if (!s) return null;
    const a = api();
    if (s.fxId && !s.keys.length) {
      const e = a.fx.get(s.fxId);
      return e ? { sentence: a.fx.sentence(e.original, { name: s.name }), fx: e.fx, original: e.original, source: e.source, key: null, why: `No hook · ${SOURCE_TAG[e.source]}` } : { sentence: 'Nothing plays.', why: '' };
    }
    const item = s.uuid ? fromUuidSync(s.uuid) : null;
    return a.sentenceFor(item ?? { name: s.name, keys: s.keys, pointer: s.pointer ?? null }, s.on, { hasPlace: s.hasPlace });
  }
  answer() { return this.answerFor(this.view.subject); }

  // -------------------------------------------------------------------------------------------
  // rendering
  // -------------------------------------------------------------------------------------------
  async _prepareContext() { if (!this.entries) this.refresh(); return {}; }

  async _renderHTML() {
    const t = this.view.tab;
    // the sheet is a pane, not a tab: while it is open the FX tab is where you are
    const on = (id) => (id === 'fx' ? t === 'fx' || t === 'editor' : t === id);
    const tab = (id, label) => `<button type="button" role="tab" aria-selected="${on(id)}" data-act="tab" data-tab="${id}">${label}</button>`;
    return `<div class="fx-wrap">
      <div class="fx-head"><div class="search head"><input type="search" class="fx-q" placeholder="What plays for…" aria-label="What plays for" autocomplete="off" value="${esc(this.view.q ?? '')}"><div class="suggest" data-open="false"></div></div></div>
      <div class="tabs" role="tablist">${TABS.map(([id, label]) => tab(id, label)).join('')}</div>
      <section class="pane" data-pane="fx" data-active="${t === 'fx'}">${t === 'fx' ? renderFx(this) : ''}</section>
      <section class="pane" data-pane="editor" data-active="${t === 'editor'}">${t === 'editor' ? renderSheet(this) : ''}</section>
      <section class="pane" data-pane="assets" data-active="${t === 'assets'}">${t === 'assets' ? renderLibrary(this) : ''}</section>
      <section class="pane" data-pane="coverage" data-active="${t === 'coverage'}">${t === 'coverage' ? this.renderCheck() : ''}</section>
      <div class="toast" data-on="false"></div>
    </div>`;
  }

  _replaceHTML(result, content) { content.innerHTML = result; }

  /** popped out (Foundry 14): fill the new window at once and follow it as it is resized */
  async _onDetach(...args) {
    const r = await super._onDetach?.(...args);
    setTimeout(() => this.fitDetached(), 50);
    return r;
  }

  fitDetached() {
    const win = this.element?.ownerDocument?.defaultView;
    if (!win || win === window) return;
    const fit = () => { try { this.setPosition({ left: 0, top: 0, width: win.innerWidth, height: win.innerHeight }); } catch { /* the window is closing */ } };
    fit();
    if (!this._fitBound) { this._fitBound = true; win.addEventListener('resize', fit); }
  }

  async _onRender() {
    if (this.element?.ownerDocument !== document) this.fitDetached();
    // the sheet's overlap strip needs the pictures' own lengths, which only the browser knows
    if (this.view.tab === 'editor' && this.sheet) hydrateSheet(this);
    if (this._bound) return;
    this._bound = true;
    const root = this.element;
    root.addEventListener('click', (ev) => this.onClick(ev));
    root.addEventListener('input', (ev) => this.onInput(ev));
    root.addEventListener('change', (ev) => this.onChange(ev));
    root.addEventListener('keydown', (ev) => this.onKey(ev));
  }

  toast(msg) {
    const t = this.element?.querySelector('.toast');
    if (!t) return;
    t.textContent = msg;
    t.dataset.on = 'true';
    clearTimeout(this._toastTimer);
    this._toastTimer = setTimeout(() => { t.dataset.on = 'false'; }, 3200);
  }

  /** the FX and starters that match a few letters, for a Start-from box */
  likeHits(q) {
    const a = api();
    const needle = q.trim().toLowerCase();
    const starters = [...a.index.starters.values()].map((st) => ({ id: st.id, words: `${idWords(st.id)} — ${st.note ?? ''}`, tag: 'starter' }));
    const fx = a.fx.list().filter((e) => !e.fx.off).map((e) => ({ id: e.fx.id, words: idWords(e.fx.id), tag: SOURCE_TAG[e.source], keys: (e.fx.for ?? []).map(keyLabel).join(', ') }));
    if (!needle) return [...starters, ...fx.slice(0, 12)];
    return [...starters, ...fx].filter((h) => h.words.toLowerCase().includes(needle) || (h.keys ?? '').toLowerCase().includes(needle)).slice(0, 12);
  }

  /** one FX as a file on the local machine, in the recipe files' own shape */
  exportFx(id) {
    const a = api();
    const e = a.fx.get(id);
    if (!e) return this.toast('Nothing to export.');
    const item = !(e.fx.for?.length);
    const meta = { schema: 2, exported: new Date().toISOString().slice(0, 10), by: game.user.name, from: MODULE_ID, ...(item ? { warning: 'Item Hook: plays nothing until an item points at it.' } : {}) };
    const text = JSON.stringify({ _meta: meta, fx: [e.original] }, null, 1);
    foundry.utils.saveDataToFile(text, 'application/json', `fx-${id}.json`);
    return this.toast(`Exported: ${idWords(id)}${item ? ' (Item Hook)' : ''}.`);
  }

  /** a file of FX read from the local machine into this world, or bound for the main corpus */
  async importFx(to) {
    const a = api();
    const file = await foundry.applications.api.DialogV2.prompt({
      window: { title: to === 'stock' ? 'Import to Stock' : 'Import FX' },
      content: '<input type="file" name="file" accept=".json,application/json">',
      ok: { label: 'Import', callback: (ev, button) => button.form.elements.file?.files?.[0] ?? null },
      rejectClose: false, modal: true,
    });
    if (!file) return undefined;
    let j;
    try { j = JSON.parse(await foundry.utils.readTextFromFile(file)); } catch (e) { return this.toast(`Not an FX file: ${e.message}`); }
    const list = Array.isArray(j) ? j : Array.isArray(j.fx) ? j.fx : j.id ? [j] : [];
    if (!list.length) return this.toast('No FX in the file.');
    let saved = 0, items = 0;
    const problems = [];
    for (const fx of list) {
      const r = await a.fx.save(fx, { by: fx.by ?? game.user.name, to: to === 'stock' ? 'stock' : undefined });
      if (!r.ok) { problems.push(`${fx.id ?? '?'}: ${r.problems.join('; ')}`); continue; }
      saved++;
      if (!(fx.for?.length)) items++;
    }
    this.refresh();
    await this.render();
    return this.toast(`Imported ${saved} FX${to === 'stock' ? ', staged: Stock' : ''}${items ? ` (${items} Item Hook)` : ''}.${problems.length ? ` Skipped: ${problems.join(' · ')}` : ''}`);
  }

  /** delete an FX for good: out of this world and out of the module's corpus files */
  async deleteFx(id) {
    const a = api();
    const e = a.fx.get(id);
    if (!e) return undefined;
    const ok = await foundry.applications.api.DialogV2.confirm({ window: { title: `Delete ${idWords(id)}?` }, content: `<p>${SOURCE_TAG[e.source] ?? e.source}${e.source === 'world' ? '' : ' file'}. Deletes it permanently.</p>`, rejectClose: false, modal: true });
    if (!ok) return undefined;
    let r;
    try { r = await a.corpus.erase(id); } catch (err) { return this.toast(`Could not delete it: ${err.message}`); }
    this.refresh();
    if (this.view.subject && this.answer()?.original?.id === id) this.view.subject = { ...this.view.subject };
    await this.render();
    return this.toast(`Deleted: ${idWords(id)}${r.written.length ? ` (${r.written.map((f) => f.split('/').pop()).join(', ')})` : ''}.`);
  }

  // ---- Check ----------------------------------------------------------------------------------
  /** every Item compendium in the world, grouped by the package that ships it */
  bookShelf() {
    const groups = new Map();
    for (const p of game.packs) {
      if (p.documentName !== 'Item') continue;
      const m = p.metadata;
      const pkg = m.packageType === 'world' ? 'This world' : m.packageType === 'system' ? (game.system.title ?? m.packageName) : (game.modules.get(m.packageName)?.title ?? m.packageName);
      (groups.get(pkg) ?? groups.set(pkg, []).get(pkg)).push({ id: p.collection, name: m.label ?? p.collection, size: p.index.size });
    }
    return [...groups.entries()].map(([pkg, books]) => ({ pkg, books: books.sort((x, y) => x.name.localeCompare(y.name)) })).sort((x, y) => x.pkg.localeCompare(y.pkg));
  }

  renderCheck() {
    const a = api();
    const V = this.view;
    const problems = a.index.problems ?? [];
    const shelf = this.bookShelf().map(({ pkg, books }) => `<div class="sub">${esc(pkg)}</div><div class="pills">${books.map((b) => `<button type="button" class="pill" aria-pressed="${V.chosenBooks.has(b.id)}" data-act="book" data-book="${esc(b.id)}">${esc(b.name)} <span class="note">${b.size}</span></button>`).join('')}</div>`).join('');
    const n = V.chosenBooks.size;
    const books = V.books;
    const tiles = books ? (() => { const asked = books.reduce((t, b) => t + b.asked, 0); const answered = books.reduce((t, b) => t + b.answered, 0); return [['', asked, 'Abilities'], ['good', answered, 'With FX'], [asked - answered ? 'warn' : 'good', asked - answered, 'No FX']]; })() : [];
    return `<div class="stack">
      <div class="card"><div class="sub">Compendiums</div>
        ${shelf || '<p class="note">No item compendiums in this world.</p>'}
        <p class="note"><button type="button" data-act="books" ${n && !V.reading ? '' : 'disabled'}>${V.reading ? 'Checking…' : n ? `Check (${n})` : 'Check'}</button></p></div>
      ${books ? `<div class="tiles">${tiles.map(([c, k, l]) => `<div class="tile ${c}"><div class="num">${k}</div><div class="l">${esc(l)}</div></div>`).join('')}</div>
      <div class="card"><div class="sub">No FX</div>${this.renderBooks(books)}</div>` : ''}
      ${problems.length ? `<div class="card"><div class="sub">Errors</div>${problems.map((p) => `<p class="bad">${esc(p)}</p>`).join('')}</div>` : ''}
      ${renderMaintain(this)}
    </div>`;
  }

  renderBooks(books) {
    return books.map((b) => `<div class="sub">${esc(b.name)} · ${b.answered} of ${b.asked}</div>${b.nothing.length ? `<div class="abilities">${b.nothing.slice(0, 200).map((n) => `<button type="button" class="pill" data-act="key" data-key="${esc(n.key)}">${dot('none')}${esc(n.name)}</button>`).join('')}${b.nothing.length > 200 ? `<span class="note">and ${b.nothing.length - 200} more</span>` : ''}</div>` : '<p class="note">All have FX.</p>'}`).join('');
  }

  async checkBooks() {
    const a = api();
    const packs = [...this.view.chosenBooks].map((id) => game.packs.get(id)).filter((p) => p?.documentName === 'Item');
    const out = [];
    for (const p of packs) {
      const docs = await p.getDocuments();
      const row = { name: p.metadata.label ?? p.collection, asked: 0, answered: 0, nothing: [] };
      for (const d of docs) {
        if (!['spell', 'feat', 'weapon', 'consumable', 'equipment', 'tool'].includes(d.type)) continue;
        const acts = d.system?.activities?.contents ?? [];
        if (!acts.length && d.type !== 'weapon') continue;
        const hasPlace = acts.some((x) => x?.target?.template?.type);
        const r = a.resolve(a.subjects.ofItem(d, { activity: acts[0] ?? null }), 'use', { hasPlace });
        row.asked++;
        if (r.fx) row.answered++;
        else row.nothing.push({ name: d.name, key: r.subject?.keys?.find((k) => !k.includes('/')) ?? r.subject?.keys?.[0] });
      }
      out.push(row);
    }
    this.view.books = out;
  }

  // -------------------------------------------------------------------------------------------
  // events
  // -------------------------------------------------------------------------------------------
  async onClick(ev) {
    const b = ev.target.closest('[data-act]');
    if (!b || !this.element.contains(b)) { if (!ev.target.closest('.search')) this.element.querySelectorAll('.suggest').forEach((x) => { x.dataset.open = 'false'; }); return undefined; }
    const act = b.dataset.act;
    if (act.startsWith('cw-') || act.startsWith('sh-')) return onSheetClick(this, b, act);
    // leaving an unlocked sheet with changes asks first
    if (['tab', 'entry', 'key', 'hit', 'new', 'create-new', 'fx-sel', 'fx-open', 'fx-edit', 'fx-dup'].includes(act) && sheetDirty(this) && !(await leaveSheet(this))) return undefined;
    if (act.startsWith('fx-')) return onFxClick(this, b, act);
    if (act.startsWith('co-')) return onCorpusClick(this, b, act);
    if (act.startsWith('lib-')) return onLibraryClick(this, b, act);
    const S = this.view;
    switch (act) {
      case 'tab': S.tab = b.dataset.tab; return this.render();
      case 'book': { const id = b.dataset.book; if (S.chosenBooks.has(id)) S.chosenBooks.delete(id); else S.chosenBooks.add(id); return this.render(); }
      case 'entry': { const item = fromUuidSync(b.dataset.uuid); if (!item) return undefined; if (b.dataset.create) this.openFor(this.subjectFromItem(item)); else this.showItem(item); return this.render(); }
      case 'effect': { const row = this.census.actors.find((r) => r.name === b.dataset.actor); const ef = row?.effects[Number(b.dataset.i)]; if (!ef) return undefined; this.showEntry({ name: ef.name, keys: ef.keys, owner: row.name, on: 'effect' }); return this.render(); }
      case 'key': this.openFor(this.subjectForKey(b.dataset.key), { edit: true }); return this.render();
      case 'hit': { const e = this.entries[Number(b.dataset.i)]; if (e) this.showEntry(e); return this.render(); }
      case 'new': this.showNew(b.dataset.name); return this.render();
      case 'new-kind': this.showNew(S.subject.name, b.dataset.kind); return this.render();
      case 'create-new': openSheet(this, { subject: S.subject, edit: true }); return this.render();
      case 'remove': return this.removeCurrent();
      case 'remove-fx': return this.removeFx(b.dataset.id);
      case 'delete-fx': return this.deleteFx(b.dataset.id);
      case 'export-fx': return this.exportFx(b.dataset.id);
      case 'import-fx': return this.importFx(b.dataset.to || null);
      case 'books': S.reading = true; await this.render(); try { await this.checkBooks(); } finally { S.reading = false; } return this.render();
      default: return undefined;
    }
  }

  onInput(ev) {
    const el = ev.target;
    if (el.className.includes('cw-') || el.className.includes('sh-')) return onSheetInput(this, el);
    if (el.className.includes('co-')) return onCorpusInput(this, el);
    if (el.classList.contains('lib-q')) return onLibraryInput(this, el);
    // the one search: the dropdown answers what plays for an ability, the letters narrow the FX list
    if (el.classList.contains('fx-q')) {
      this.view.q = el.value;
      if (!el.value.trim() && this.view.subject) { this.view.subject = null; this.view.fxSel = null; }
      this.suggest(el);
      if (this.fxv) this.fxv.show = 200;
      clearTimeout(this._qTimer);
      this._qTimer = setTimeout(() => this.narrow(), 250);
    }
    return undefined;
  }

  /** the FX list alone, redrawn as the header search is typed in, keeping the caret where it is */
  narrow() {
    const pane = this.element?.querySelector('[data-pane="fx"][data-active="true"]');
    if (!pane) return;
    const rows = pane.querySelector('.rows');
    const top = rows?.scrollTop ?? 0;
    pane.innerHTML = renderFx(this);
    const again = pane.querySelector('.rows');
    if (again) again.scrollTop = top;
  }

  onChange(ev) {
    const el = ev.target;
    if (el.className.includes('cw-') || el.className.includes('sh-')) return onSheetChange(this, el);
    if (el.className.includes('co-')) return onCorpusChange(this, el);
    if (el.classList.contains('fx-stage')) return onFxChange(this, el);
    if (el.className.includes('lib-')) return onLibraryChange(this, el);
    return undefined;
  }

  onKey(ev) {
    const el = ev.target;
    if (ev.key === 'Escape') { this.element.querySelectorAll('.suggest').forEach((x) => { x.dataset.open = 'false'; }); return; }
    if ((el.className.includes('cw-') || el.className.includes('sh-')) && onSheetKey(this, ev)) return;
    if (ev.key !== 'Enter') return;
    if (el.classList.contains('fx-q')) {
      ev.preventDefault();
      const q = el.value.trim();
      if (!q) return;
      const hits = this.searchHits(q);
      const exact = hits.find((h) => h.e.name.toLowerCase() === q.toLowerCase()) ?? hits[0];
      if (exact) this.showEntry(exact.e); else this.showNew(q);
      this.render();
    }
  }

  /** one row per ability: the corpus first (main, then this table's), then what sits on a sheet with no FX yet */
  searchHits(q) {
    const needle = q.trim().toLowerCase();
    if (!needle) return [];
    const out = [];
    this.entries.forEach((e, i) => { if (e.name.toLowerCase().includes(needle)) out.push({ e, i }); });
    const rank = (e) => (e.status === 'stock' ? 0 : e.status === 'custom' ? 1 : e.status === 'off' ? 2 : 3);
    out.sort((x, y) => rank(x.e) - rank(y.e) || x.e.name.localeCompare(y.e.name) || (x.e.actorType === 'character' ? 0 : 1) - (y.e.actorType === 'character' ? 0 : 1));
    const seen = new Set();
    return out.filter(({ e }) => { const k = `${e.keys.join('|')}|${e.status}`; if (seen.has(k)) return false; seen.add(k); return true; }).slice(0, 12);
  }

  /** the right-hand word on a suggestion: where the FX comes from, or whose sheet it waits on */
  hitWhere(e) {
    if (e.status === 'none' && e.owner) return `${e.owner} · ${STATUS_WORDS.none}`;
    return STATUS_WORDS[e.status] ?? '';
  }

  suggest(input) {
    const box = input.parentElement.querySelector('.suggest');
    const q = input.value.trim();
    if (!q) { box.dataset.open = 'false'; return; }
    const hits = this.searchHits(q);
    box.innerHTML = hits.map(({ e, i }) => `<div class="hit" data-act="hit" data-i="${i}"><span>${dot(e.status)}${esc(e.name)}${e.effect ? ' <span class="note">effect</span>' : ''}</span><span class="o">${esc(this.hitWhere(e))}</span></div>`).join('')
      + `<div class="hit" data-act="new" data-name="${esc(q)}"><span class="o">New ability: “${esc(q)}”</span></div>`;
    box.dataset.open = 'true';
  }

  // -------------------------------------------------------------------------------------------
  // doing things: remove (saving is the sheet's, ui/sheet.js)
  // -------------------------------------------------------------------------------------------
  async removeCurrent() {
    const a = api();
    const s = this.view.subject;
    const r = this.answer();
    const id = r?.original?.id ?? (r?.off ? a.fx.buffer().find((l) => l.off && (l.for ?? []).some((k) => s.keys.includes(k)))?.id : null);
    const item = s.uuid ? fromUuidSync(s.uuid) : null;
    if (item && s.pointer) await item.unsetFlag(MODULE_ID, 'fx');
    if (id && a.fx.get(id)?.source === 'world') await a.fx.remove(id);
    this.refresh();
    if (item) this.showItem(item);
    await this.render();
    return this.toast(`Reverted: ${s.name}.`);
  }

  async removeFx(id) {
    const a = api();
    const ok = await foundry.applications.api.DialogV2.confirm({ window: { title: 'Revert FX?' }, content: `<p>${esc(idWords(id))} returns to its previous FX, or to none.</p>`, rejectClose: false });
    if (!ok) return undefined;
    await a.fx.remove(id);
    this.refresh();
    await this.render();
    return this.toast(`Reverted: ${idWords(id)}.`);
  }
}

// an open window follows the corpus: an FX saved through the API from elsewhere (a macro, an assistant) shows at once
Hooks.on('fxstudio.rebuilt', () => { const app = Studio.current; if (app?.rendered) { app.refresh(); app.render(); } });
